---
name: ClearLag
version: 2.0.0
main: tobias14\clearlag\ClearLag
src-namespace-prefix: tobias14\clearlag
api: 4.0.0
author: tobias14
website: https://github.com/Tobias-2006/ClearLag

permissions:
  clearlag.command:
    description: Allows to use the /clearlag command
    default: op
...
